### ISSUE TITLE
Response with "alternate" sub status breaks validation

### ISSUE THREAD

**Issue by pomma89** [zerobounce/zero-bounce-python-sdk-setup#2]
As described in #1, `ZBValidateSubStatus` is missing new sub statuses, which breaks validation when one of them is included in ZeroBounce response:

```
Unhandled exception
Traceback (most recent call last):
  File "/opt/app/.venv/lib/python3.11/site-packages/zerobouncesdk/zerobouncesdk.py", line 271, in __request
    response_object = response_class(response)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app/.venv/lib/python3.11/site-packages/zerobouncesdk/zb_validate_response.py", line 75, in __init__
    self.sub_status = None if self.sub_status is None else ZBValidateSubStatus(self.sub_status)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 715, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1131, in __new__
    raise ve_exc
ValueError: 'alternate' is not a valid ZBValidateSubStatus
```

#1 should fix this kind of error by adding missing definitions. Could you check that out?

Thanks,
Alessio

**Comment by antonio-bigan** [comment]
Hello @pomma89,
The new release handles this problem.

**Comment by pomma89** [comment]
Thank you 👍
